### ISSUE TITLE
后台小组

### ISSUE THREAD

**Issue by yongxin3344520** [BCSquad/pmph#5]
创建小组以及后面相关小组的操邹中book_id ，和 note 字段均为涉及，依据目前的设计是否考虑去掉这两个字段？

**Comment by gugia** [comment]
新设计中，教材申报模块中将加入“创建小组”功能，用户可通过某书目下的按钮直接创建小组，之后在小组界面可显示[教材]-[书籍]，借此可实现更多扩展功能。

**Comment by gugia** [comment]
note作为备注应在创建小组时提供给用户填写（可选）
